server.error.includeStacktrace: NEVER

jwt.secret: yadajwt

yada:
  recaptcha: recaptcha.GoogleCN
  admin:
    ipWhitelist: /127.0.0.1,/0:0:0:0:0:0:0:1
spring:
  cloud:
    gateway:
      metrics:
        enabled: true