#logging.level:
#    org.springframework: TRACE
server:
  error:
    includeStacktrace: ALWAYS

yada.contextPath: /gw

spring.cloud.gateway.routes:
  - uri: http://localhost:3010
    predicates:
      - App=${yada.contextPath:}/app/app-1
    filters:
      - Auth
  - uri: http://localhost:3011
    predicates:
      - Svc=${yada.contextPath:}/svc,service-1
    filters:
      - ApiAuth
  - uri: http://localhost:8080
    predicates:
      - Path=${yada.contextPath:}/**
    filters:
      - RewritePath=${yada.contextPath:}(?<segment>/?.*),$\{segment}

management.endpoints:
  web.exposure.include: metrics,gateway
  health.show-details: always

#yada.security:
#  defaultPwd: changepwd
#  recaptcha: recaptcha.None
#  pwdStrength: 1
#  token:
#    secret: yadajwt
#    expire: 3600

#yada.db.mongo.uri: 'mongodb://localhost/yada_auth?replicaSet=rs'


