server.error.includeStacktrace: NEVER

jwt.secret: yadajwt

spring.cloud.gateway.routes:
  - uri: http://localhost:3000
    predicates:
      - App=/app1
    filters:
      - Auth
  - uri: http://localhost:3000
    predicates:
      - Svc=/svc,service-1
    filters:
      - AuthApi