logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
server:
  error:
    includeStacktrace: ALWAYS

spring.cloud.gateway.routes:
  - uri: http://localhost:3010
    predicates:
      - App=/app/app-1
    filters:
      - Auth
  - uri: http://localhost:3011
    predicates:
      - Svc=/svc,service-1
    filters:
      - AuthApi
  - uri: http://localhost:3011
    predicates:
      - Path=/abc

management.endpoints:
  web.exposure.include: metrics,gateway
  health.show-details: always

yada:
  recaptcha: recaptcha.GoogleCN


